name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
version: 2.0.0-dev

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  dio: 
  source_gen: 
  built_collection:
  code_builder: 
  tuple: 
  retrofit: 
  dart_style: 
  analyzer: 
  build: 
dev_dependencies:
  test:
  source_gen_test: 
  resource:
