kind: pipeline
name: default

steps:
  - name: test
    image: google/dart
    commands:
      - cd example && dart pub get && dart --no-sound-null-safety pub run build_runner build
      - PKGS="example annotation generator" ./tool/travis.sh dartanalyzer
      - cd generator
      - dart pub get
      - dart --no-sound-null-safety pub run test
      - cd example && dart pub get && dart --no-sound-null-safety pub run test
